# Generated by Django 4.1.7 on 2023-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'In progress'), ('FU', 'Fulfilled'), ('RE', 'Rejected')], default='PR', max_length=2),
        ),
    ]
