# Generated by Django 4.1.7 on 2023-03-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
    ]
